project:
  type: website
  output-dir: docs

website:
  title: "Neil Lenhoff"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: about.qmd
      - text: Data Visualization
        menu:
          - text: Birth in Canada Visualization
            href: Data_Visualization.qmd
          - text: Movie Couples Visualization
            href: Data_Visualization_2.qmd
          - text: The Office Text Analysis
            href: Text_Analysis.qmd
          - text: Penguin Simulation Study
            href: Simulation_Study.qmd
          - text: Ethics- Data and Power
            href: Ethics- Data and Power.qmd
          - text: SQL Policing Policy Project
            href: SQL_Project.qmd
          - text: Penguins Presentation
            href: Pittsburgh_Penguin_Presentation.qmd


format:
  html:
    theme: 
      light: lux
      dark: cyborg
    css:
      - styles.css
      - typography.css

