project:
  type: website
  output-dir: docs

website:
  title: "Neil Lenhoff"
  navbar:
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - resources.qmd
     - href: Data Visualization.qmd
       text: Data Visualization
     - href: Data Visualization 2.qmd
       text: Data Visualization 2

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css

