project:
  type: website
  output-dir: docs

website:
  title: "Neil Lenhoff"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Resources
        href: resources.qmd
      - text: Data Visualization
        menu:
          - text: Visualization 1
            href: Data_Visualization.qmd
          - text: Visualization 2
            href: Data_Visualization_2.qmd
          - text: Text Analysis
            href: Text_Analysis.qmd

      
            


format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css

